# Site settings
title: BAEKJungHo
url: "https://BAEKJungHo.github.io"
baseurl: ""
description: >
    BAEKJungHo Blog

# My information
email: qjxjfld13@gmail.com
author: BAEKJungHo
profile: ISFJ
twitter_username: BAEKJungHo
github_username: BAEKJungHo
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id: BAEKJH
  shortname: BAEKJH
utterances:
  repo: BAEKJungHo/BAEKJungHo.github.io
  issue-term: url
  label: Comment
  branch: master

google_analytics:
  ua: UA-189505063-1

google_adsense:
  client: ca-pub-3675948545737694

blame: "https://github.com/BAEKJungHo/BAEKJungHo.github.io/tree/master/_wiki"
edit: "https://github.com/BAEKJungHo/BAEKJungHo.github.io/edit/master/_wiki"
issue: "https://github.com/BAEKJungHo/BAEKJungHo.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
